debug: false

################## [SERVER] #################
server:
  port: ${SERVER_PORT:8086}
  compression:
    enabled: true
  servlet:
    context-path: ${SERVER_CONTEXT:/api}
    


################## [SPRING] #################
spring:
    
  h2:
    console:
      enabled: true
      path: /h2-console

  main:
    banner-mode: console
    log-startup-info: true
    
  devtools:
    restart:
      enabled: true

#  datasource:
#    url: jdbc:${DATABASE_VENDOR:postgresql}://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:notification}
#    username: ${DATABASE_USER:postgres}
#    password: ${DATABASE_PASSWORD:postgres}
#    driver-class-name: ${DATABASE_VENDOR_DRIVER:org.postgresql.Driver}
   
  datasource:
    url: jdbc:h2:mem:wex;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DATABASE_USER:h2_user}
    password: ${DATABASE_PASSWORD:h2_pass}
    driver-class-name: ${DATABASE_VENDOR_DRIVER:=org.h2.Driver}
    
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
        
  flyway:
    enabled: true
    

################## [LOGGING] #################
logging:
  level:
    root: DEBUG
    br.com.bentiviu: ERROR
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: TRACE
#    io.swagger.models.parameters.AbstractSerializableParameter: WARN
#    io.swagger.models.parameters: ERROR
#    org.springframework.boot.context.config.ConfigFileApplicationListener: ERROR
#    org.hibernate.SQL: WARN
#    org.apache.http.wire: WARN
#    org.springframework.orm.jpa.JpaTransactionManager: WARN
#    org.postgresql.jdbc.PgConnection: WARN
#    javax.xml.bind: OFF
#
#    com:
#      hazelcast: WARN
#      zaxxer:
#        hikari: OFF
#      fasterxml:
#        jackson:
#          databind: WARN
#    org:
#      postgresql: WARN
#      apache: ERROR
#      hibernate: ERROR
#      springframework: ERROR
        
