debug: false

################## [SERVER] #################
server:
  port: ${SERVER_PORT:8086}
  compression:
    enabled: true
  servlet:
    context-path: ${SERVER_CONTEXT:/api}
    


################## [SPRING] #################
spring:
    
  h2:
    console:
      enabled: true
      path: /h2-console

  main:
    banner-mode: console
    log-startup-info: true
    
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:h2:mem:wex;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DATABASE_USER:h2_user}
    password: ${DATABASE_PASSWORD:h2_pass}
    driver-class-name: ${DATABASE_VENDOR_DRIVER:=org.h2.Driver}
    
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
        
  flyway:
    enabled: true
    

################## [LOGGING] #################
logging:
  level:
    root: DEBUG
    br.com.thomas.wex: ERROR

        
