debug: false

################## [SERVER] #################
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  servlet:
    context-path: ${SERVER_CONTEXT}

################## [SPRING] #################
spring:

  devtools:
    restart:
      enabled: false


################## [LOGGING] #################
logging:
  level:
    root: ERROR
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    io.swagger.models.parameters.AbstractSerializableParameter: WARN
    io.swagger.models.parameters: ERROR
    org.springframework.core.env.PropertySourcesPropertyResolver: DEBUG
    org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG
    javax.management.remote.rmi: WARN
    org.apache.catalina.loader: WARN
    sun: ERROR
    org.apache.http.wire: WARN
    com.fasterxml.jackson.databind: WARN
    br.com.thomas.wex: WARN

    org:
      hibernate:
        SQL: WARN
      springframework:
        security: DEBUG
        
################## [SWAGGER] #################

